version: '3'

services: 
    api-server:
        container_name: "myflix-api-server"
        build:
            context: ./server
        volumes:
            - ./server:/app
            - /app/node_modules
            - ./server/images:/app/images
        ports:
            - 3001:3000
            - 9229:9229
        environment: 
            - MEDIA_FILES_PATH=files
            - MONGO_URL=mongodb://myflix:m0ng0p455very53cur3123@myflix-mongo:27017/
            - SESSION_SECRET=s3cur3th15w311pl3453
    web-server:
        container_name: "myflix-web-server"
        build:
            context: ./web
        volumes:
            - ./web/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./server/files:/files
            - ./server/exported-files:/exported-files
        ports:
            - 8010:80
            - 8011:81
            - 8012:82
    mongo:
        container_name: "myflix-mongo"
        image: mongo:4.0.23-xenial
        ports:
            - "27020:27017"
        volumes:
            - ./mongoDB:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: myflix
            MONGO_INITDB_ROOT_PASSWORD: m0ng0p455very53cur3123
