version: '3'

services: 
    api-server:
        container_name: "myflix-api-server"
        build:
            context: ./server
        volumes:
            - ./server:/app
            - /app/node_modules
            - ./server/images:/app/images
        ports:
            - 3001:3000
            - 9229:9229
        environment: 
            - MEDIA_FILES_PATH=files
    web-server:
        container_name: "myflix-web-server"
        build:
            context: ./web
        volumes:
            - ./web/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./server/files:/files
        ports:
            - 8010:80
            - 8011:81
