version: '3'

services: 
  apache:
    container_name: "apache-server"
    image: httpd:2.4
    volumes:
      - ./files:/usr/local/apache2/htdocs/
    ports:
      - 8009:80
  api-server:
    container_name: "api-server"
    build:
      context: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3001:3000
      - 9229:9229
    environment: 
      - MEDIA_FILES_PATH=files
